// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA8X0vwfxdxKAfKVMzsWJZ0-RrgjlBddM',
    appId: '1:599203249787:web:7ceb5e23bbfb0b36dd6cde',
    messagingSenderId: '599203249787',
    projectId: 'maamaas-3c567',
    authDomain: 'maamaas-3c567.firebaseapp.com',
    storageBucket: 'maamaas-3c567.firebasestorage.app',
    measurementId: 'G-PXVWFXLGK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8xMDdg7cjxhBugci5CkJXWptPRjq_ebQ',
    appId: '1:599203249787:android:67e418c447726c95dd6cde',
    messagingSenderId: '599203249787',
    projectId: 'maamaas-3c567',
    storageBucket: 'maamaas-3c567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlPRzwOXI9-41UD379Hhwuwtp86kHLvA',
    appId: '1:599203249787:ios:b2bd901f5441a9c4dd6cde',
    messagingSenderId: '599203249787',
    projectId: 'maamaas-3c567',
    storageBucket: 'maamaas-3c567.firebasestorage.app',
    iosBundleId: 'com.example.maamaasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqlPRzwOXI9-41UD379Hhwuwtp86kHLvA',
    appId: '1:599203249787:ios:b2bd901f5441a9c4dd6cde',
    messagingSenderId: '599203249787',
    projectId: 'maamaas-3c567',
    storageBucket: 'maamaas-3c567.firebasestorage.app',
    iosBundleId: 'com.example.maamaasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA8X0vwfxdxKAfKVMzsWJZ0-RrgjlBddM',
    appId: '1:599203249787:web:f3493689c9f99ecadd6cde',
    messagingSenderId: '599203249787',
    projectId: 'maamaas-3c567',
    authDomain: 'maamaas-3c567.firebaseapp.com',
    storageBucket: 'maamaas-3c567.firebasestorage.app',
    measurementId: 'G-K0GE01251B',
  );
}
